<!DOCTYPE html>
<meta charset="utf-8">
<link href="style.css" rel="stylesheet">
<body>
    <h1>Formulaire de création de compte</h1>

    <form class="signupbox" action="create_user.php" method="post">
        <div>
            <label for="firstname">Votre nom :</label>
            <input type="text" name="firstname">
        </div>

        <div>
            <label for="lastname">Votre prénom :</label>
            <input type="lastname" name="lastname">
        </div>

        <div>
            <label for="email">Votre email :</label>
            <input type="email" name="email">
        </div>

        <div>
            <label for="password">Mot de passe :</label>
            <input type="password" name="password">
        </div>

        <input type="submit" value="Enregistrer">

    </form>

</body>